### ISSUE TITLE
Confirm MRW_ENHANCED_GROUPING_NO_MIRRORING is set correctly.

### ISSUE THREAD

**Issue by williamspatrick** [open-power/palmetto-xml#17]
See open-power/op-build#493 .

**Comment by bwmashak** [comment]
Today I pushed palmetto.xml which -> Changed MRW_ENHANCED_GROUPING_NO_MIRRORING from true -> false to work with mss_eff_grouping.C v1.37 or newer.

**Comment by bwmashak** [comment]
This change was not needed for palmetto because it only contains 1 memory buffer and the change is only needed for systems with more than 2 memory buffers per socket.  While it wasn't needed, it shouldn't hurt either.
